check bucket status using head-bucket and store result in a variable

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,11 +68,10 @@ commands:
           when: on_fail
           command: |
             bucketstatus=$(aws s3api head-bucket --bucket udapeople-${OldWorkflowID} 2>&1)
-            if echo "${bucketstatus}" | grep 'Not Found';
-              then
-                echo "bucket does not exist"
-              else
-                aws s3 rm s3://udapeople-<< parameters.WorkflowID >> --recursive
+            if echo "${bucketstatus}" | grep 'Not Found';then
+              echo "bucket does not exist"
+            else
+              aws s3 rm s3://udapeople-<< parameters.WorkflowID >> --recursive
             fi
             aws cloudformation delete-stack \
             --stack-name udapeople-frontend-<< parameters.WorkflowID >>
@@ -92,8 +91,7 @@ commands:
           command: |
             LAST_MIGRATION_STATE=$(curl --insecure  https://kvdb.io/RMktn9tdJcK4CjcEV3o6uv/migration_<< parameters.Workflow_ID >>)
             # Logic for reverting the database state
-            if (( $LAST_MIGRATION_STATE == 1 ));
-              then
+            if (( $LAST_MIGRATION_STATE == 1 ));then
               cd ~/project/backend
               npm install
               npm run migration:revert
@@ -281,8 +279,7 @@ jobs:
       - run:
           name: Send migration results to kvdb.io
           command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt;then
               # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
               #curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
               # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
@@ -377,9 +374,7 @@ jobs:
             # your code here
             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
             echo ${URL}
-            if curl -s ${URL} | grep "Welcome"
-            then
-              # Change this to 0 after the job fails
+            if curl -s ${URL} | grep "Welcome";then
               exit 0
             else
               exit 1
@@ -395,11 +390,10 @@ jobs:
             echo "${BACKEND_IP}"
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
-              then
-                exit 0
-              else
-                exit 1
+            if curl "${API_URL}/api/status" | grep "ok";then
+              exit 0
+            else
+              exit 1
             fi
       # Here's where you will add some code to rollback on failure
       - destroy-environment
@@ -461,17 +455,15 @@ jobs:
             # You can use any condition like:
             # if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
             # if [[ "${OldWorkflowID}" =~ "${STACKS[@]}"  ]]
-            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" =~ "${OldWorkflowID}" ]]
-              then
-                bucketstatus=$(aws s3api head-bucket --bucket udapeople-${OldWorkflowID} 2>&1)
-                if echo "${bucketstatus}" | grep 'Not Found';
-                then
-                    echo "bucket does not exist"
-                  else
-                    aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-                fi
-                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" =~ "${OldWorkflowID}" ]];then
+              bucketstatus=$(aws s3api head-bucket --bucket udapeople-${OldWorkflowID} 2>&1)
+              if echo "${bucketstatus}" | grep 'Not Found';then
+                echo "bucket does not exist"
+              else
+                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              fi
+              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
             fi
 
 workflows:
